### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jstinesnc** [mcoliver/fixPodcastMetadata#1]
This works great. Thank you for writing this! What a shame Garmin won't do it. 

When I sync using Mac Sonoma Apple Podcasts to Fenix 6X Pro, the podcasts often go to Other on the watch rather than Podcasts. 

I found the following discussion and wondered if filling a couple more tags could fix that issue, as well:

https://forums.garmin.com/sports-fitness/running-multisport/f/forerunner-945-lte/336641/podcasts-not-syncing-properly-since-15-19

But at least I can get see the files in Other and play them, so big kudos for writing this!

**Comment by jstinesnc** [comment]
I tried running your code locally with the following addition, and the files show up in Podcasts now on my Garmin 6X Pro watch. Woot!  Thanks again!

mp3.tags['genre'] = "Podcast"

**Comment by mcoliver** [comment]
Thanks. Feel free to submit a PR and I'll merge or alternately I can add it.  Let me know.
